INSERT INTO Company
VALUES('Battalion Chief 01', 1, GETDATE());
GO
INSERT INTO Company
VALUES('Bomb Squad 01', 1, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 01', 1, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 08', 1, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 01', 1, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 03', 2, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 06', 3, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 07', 4, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 07', 4, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 10', 5, GETDATE());
GO
INSERT INTO Company
VALUES('Battalion Chief 02', 6, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 02', 6, GETDATE());
GO
INSERT INTO Company
VALUES('Rescue 2', 6, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 04', 7, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 04', 7, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 13', 8, GETDATE());
GO
INSERT INTO Company
VALUES('Red Ball 1', 9, GETDATE());
GO
INSERT INTO Company
VALUES('Red Ball 2', 9, GETDATE());
GO
INSERT INTO Company
VALUES('Red Ball 3', 9, GETDATE());
GO
INSERT INTO Company
VALUES('Battalion Chief 09', 10, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 09', 10, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 09', 10, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 12', 11, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 15', 12, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 15', 12, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 16', 13, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 20', 14, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 21', 15, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 21', 15, GETDATE());
GO
INSERT INTO Company
VALUES('Battalion Chief 11', 16, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 11', 16, GETDATE());
GO
INSERT INTO Company
VALUES('Hazmat 11', 16, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 11', 16, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 14', 17, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 17', 18, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 18', 19, GETDATE());
GO
INSERT INTO Company
VALUES('Truck 18', 19, GETDATE());
GO
INSERT INTO Company
VALUES('Engine 19', 20, GETDATE());
